# Generated by Django 5.2.8 on 2025-11-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsored_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('CTA_text', models.CharField(blank=True, max_length=255, null=True)),
                ('CTA_link', models.URLField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
